# generated by datamodel-codegen:

from __future__ import annotations
from pydantic import AwareDatetime, BaseModel, Field
from typing import Literal


class UnsupportedFile(BaseModel):
    file_name: str = Field(..., description="File name as it appears in the archive.")
    present_in: Literal["base", "new", "both"] = Field(
        ..., description="Which archive(s) contain this file."
    )


class ColumnEntry(BaseModel):
    name: str = Field(..., description="Column name.")
    position: int = Field(
        ..., description="1-based position of this column in the CSV header row.", ge=1
    )


class FeedSource(BaseModel):
    source: str = Field(..., description="URL or local path to the GTFS archive.")
    downloaded_at: AwareDatetime = Field(
        ..., description="ISO 8601 timestamp of when the feed was downloaded."
    )


class FileSummary(BaseModel):
    file_name: str = Field(..., description="Name of the GTFS file.")
    status: Literal["added", "deleted", "modified", "not_compared"] = Field(
        ..., description="File-level status."
    )


class Truncated(BaseModel):
    is_truncated: Literal[True] = Field(..., description="Always true when present.")
    omitted_count: int = Field(
        ..., description="Number of row changes omitted due to the cap.", ge=1
    )


class NotComparedReason(BaseModel):
    code: str = Field(
        ...,
        description='Machine-readable reason code (e.g. "id_churn", "missing_primary_key", "file_too_large").',
    )
    message: str = Field(
        ...,
        description="Human-readable explanation of why the file or column was not compared.",
    )


class IgnoredColumn(BaseModel):
    column: str = Field(..., description="The column name that was ignored.")
    reason: NotComparedReason


class ColumnStat(BaseModel):
    column: str = Field(..., description="The column name.")
    modifications_count: int = Field(
        ...,
        description="Number of modified rows that had a change in this column.",
        ge=0,
    )
    modifications_percentage: float = Field(
        ...,
        description="modifications_count as a percentage of total modified rows.",
        ge=0.0,
        le=100.0,
    )


class RowAdded(BaseModel):
    identifier: dict[str, str] = Field(
        ..., description="Primary key values identifying this row."
    )
    raw_value: str = Field(
        ...,
        description="The CSV row from the new file as a comma-separated string. Field order matches the columns array, which preserves the raw CSV column order of the base feed (new-feed-only columns appended).",
    )
    new_line_number: int = Field(
        ..., description="1-based line number of this row in the new CSV file.", ge=1
    )


class RowDeleted(BaseModel):
    identifier: dict[str, str] = Field(
        ..., description="Primary key values identifying this row."
    )
    raw_value: str = Field(
        ...,
        description="The CSV row from the base file as a comma-separated string. Field order matches the columns array, which preserves the raw CSV column order of the base feed (new-feed-only columns appended).",
    )
    base_line_number: int = Field(
        ..., description="1-based line number of this row in the base CSV file.", ge=1
    )


class FieldChange(BaseModel):
    field: str = Field(..., description="The column name that changed.")
    base_value: str = Field(..., description="The value in the base feed.")
    new_value: str = Field(..., description="The value in the new feed.")


class RowModified(BaseModel):
    identifier: dict[str, str] = Field(
        ..., description="Primary key values identifying this row."
    )
    raw_value: str = Field(
        ...,
        description="The base CSV row as a comma-separated string. Field order matches the columns array, which preserves the raw CSV column order of the base feed (new-feed-only columns appended).",
    )
    base_line_number: int = Field(
        ..., description="1-based line number of this row in the base CSV file.", ge=1
    )
    new_line_number: int = Field(
        ..., description="1-based line number of this row in the new CSV file.", ge=1
    )
    field_changes: list[FieldChange] = Field(
        ..., description="List of field-level changes.", min_length=1
    )


class Metadata(BaseModel):
    schema_version: str = Field(..., description="The version of the schema.")
    generated_at: AwareDatetime = Field(
        ..., description="ISO 8601 timestamp of when the diff was generated."
    )
    row_changes_cap_per_file: int | None = Field(
        ...,
        description="Maximum number of row changes included per file in file_diffs. 0 means no row changes are included; null means no cap is applied.",
        ge=0,
    )
    base_feed: FeedSource
    new_feed: FeedSource
    unsupported_files: list[UnsupportedFile]


class Summary(BaseModel):
    total_changes: int = Field(
        ..., description="Total number of changes across all files.", ge=0
    )
    files_added_count: int = Field(..., description="Number of files added.", ge=0)
    files_deleted_count: int = Field(..., description="Number of files deleted.", ge=0)
    files_modified_count: int = Field(
        ..., description="Number of files modified.", ge=0
    )
    files_not_compared_count: int = Field(
        ...,
        description="Number of files that could not be meaningfully compared.",
        ge=0,
    )
    files: list[FileSummary]


class RowChanges(BaseModel):
    primary_key: list[str] = Field(
        ..., description="Column(s) that uniquely identify a row.", min_length=1
    )
    columns: list[str] = Field(
        ...,
        description="Union of all columns across both base and new versions. Order matches the base feed's original column order; columns only in the new feed are appended.",
    )
    added: list[RowAdded] = Field(..., description="Added rows (capped).")
    deleted: list[RowDeleted] = Field(..., description="Deleted rows (capped).")
    modified: list[RowModified] = Field(..., description="Modified rows (capped).")


class FileStats(BaseModel):
    total_rows_base: int | None = Field(
        None, description="Total number of rows in the base version of the file.", ge=0
    )
    total_rows_new: int | None = Field(
        None, description="Total number of rows in the new version of the file.", ge=0
    )
    columns_added_count: int | None = Field(
        None, description="Number of columns added.", ge=0
    )
    columns_deleted_count: int | None = Field(
        None, description="Number of columns deleted.", ge=0
    )
    rows_added_count: int | None = Field(
        None, description="True count of rows added.", ge=0
    )
    rows_deleted_count: int | None = Field(
        None, description="True count of rows deleted.", ge=0
    )
    rows_modified_count: int | None = Field(
        None, description="True count of rows modified.", ge=0
    )
    rows_changed_percentage: float | None = Field(
        None,
        description="Percentage of rows that were added, deleted, or modified relative to the larger of the two versions.",
        ge=0.0,
        le=100.0,
    )
    column_stats: list[ColumnStat] | None = Field(
        None,
        description="Per-column modification statistics. Only covers modified rows.",
    )


class FileDiff(BaseModel):
    file_name: str = Field(..., description="Name of the GTFS file.")
    file_action: Literal["modified", "added", "deleted", "not_compared"] = Field(
        ..., description="Action describing how this file changed."
    )
    not_compared_reason: NotComparedReason | None = None
    ignored_columns: list[IgnoredColumn] | None = Field(
        None,
        description="Columns excluded from the diff because their values are unreliable (e.g. they reference a file that was not compared).",
    )
    columns_added: list[ColumnEntry] | None = Field(
        None,
        description="Columns added to this file, in the order they appear in the new file's CSV header. Each entry includes the column name and its 1-based position in that header.",
    )
    columns_deleted: list[ColumnEntry] | None = Field(
        None,
        description="Columns deleted from this file, in the order they appeared in the base file's CSV header. Each entry includes the column name and its 1-based position in that header.",
    )
    row_changes: RowChanges | None = None
    truncated: Truncated | None = None
    stats: FileStats | None = None


class GtfsDiff(BaseModel):
    """
    Schema for GTFS Diff v2 output: a single JSON document describing all differences between two GTFS archives.
    """

    metadata: Metadata
    summary: Summary
    file_diffs: list[FileDiff]


__all__ = [
    "UnsupportedFile",
    "ColumnEntry",
    "FeedSource",
    "FileSummary",
    "Truncated",
    "NotComparedReason",
    "IgnoredColumn",
    "ColumnStat",
    "RowAdded",
    "RowDeleted",
    "FieldChange",
    "RowModified",
    "Metadata",
    "Summary",
    "RowChanges",
    "FileStats",
    "FileDiff",
    "GtfsDiff",
]
